chore(dev): :heavy_plus_sign: add nodemon for better DX
serverwentdown/file-manager pull request #20
Opened 2021-12-04 12:32 UTC by iamaamir

2021-12-09 02:57 UTC, serverwentdown requested changes
Awesome! Thanks for contributing

2021-12-09 02:57 UTC, serverwentdown commented on index.js
> +  extended: true
I feel like `extended` is not necessary as it isn't used yet. We can enable it when it is needed.

2021-12-09 02:57 UTC, serverwentdown commented on index.js
> +app.use(express.json());
Why is this needed?

2021-12-09 02:57 UTC, serverwentdown commented on index.js
> +    saveUninitialized: true
```suggestion
    resave: false,
    saveUninitialized: false
```

Avoids [saving cookies when not needed](https://github.com/expressjs/session#resave)

2021-12-28 05:35 UTC, iamaamir commented
closing in favor of #22

2021-12-28 05:35 UTC, closed without merging